language: ruby
rvm:
- 2.3.1
services:
- postgresql
cache: bundler
deploy:
  provider: heroku
  api_key:
    secure: Yp1B+1jagQvn3MHDK8Yb20WiggliQsag9Ol9jbeEyzpsiFyALiPgxXb5ve7sPdHUGzitJ75AiPwcj0rnpCn0VIMOTbeNsTb/qzTzAdRr1JTTfqxD30wtDZ+a3KGEEYKPLmArO6OFjsCCBtUYIZljbqNC79MbC2vaHmhsVkaDePaUmxtPu3mSjnLymo1ThQm5ouj7WYBQY2m1rb4s4Kd690kuox0562aZUT6cuNVCnBpmjsccsFFcudgAFBMWGAVF0Vu4D8PW59r56wlVGqwFWi3zGu4VhUekhMv5Befye1DgLBQBQ4v3uX4j9DU7zITmlZ7EZ1DsUB+GmJdBCSxzXtPSGpeStiV1egAwyByPwF6bkRFBbEsip7XX2xoI/YEUyWHcketwwVf68Epm1mohtwNcljXXsRQZuwvnJ0V+UDDMywOrWI2RmS8XPcZSkm8CPyIFSkoC9LagMfrktx+LaSUKNiAB8HFAjHGObmSoSVS8SMgRyT9saM0QRvpp88CtGpsYL2vtIbXrtmruye+gI27cRjp7o/Z5okBzmEZBAEXC6C3Wi4W2VcCsINUKecWbQPaJvHrzBjoKdmZX2LIpMmwHrWs5NbBkHHhmTpu7j1+6mfCbemc1KkukvhGo5iQwNKJDEoZ9CmKoPrCSh+ouuG485mwyQcp2qnzLeo0yLEQ=
  app: gnomad
  on:
    repo: chi-bumblebees-2017/gnomad
  before_script: bundle exec rails db:setup
